import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './ui/Shared/Navbar'
import Footer from './ui/Shared/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Pension Attrium',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='max-w-7xl mx-auto min-h-screen flex flex-col'>
          <div className=''>
            <Navbar />
          </div>

          {children}

          <div className=' sticky top-full bg-slate-900 text-gray-50 px-6 py-12 rounded-lg mb-4'>
            <Footer />
          </div>
        </div>
      </body>
    </html>
  )
}
